<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\car_sport.png" />
    <None Remove="Resources\Images\Icons\Door.png" />
    <None Remove="Resources\Images\Icons\Open.png" />
    <None Remove="Resources\Images\Icons\Plus.png" />
    <None Remove="Resources\Images\Icons\Save.png" />
    <None Remove="Resources\Images\Icons\Share.png" />
    <None Remove="Resources\Images\Matrix_River.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\SaveData\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\Abstract_AI_Art.png" />
    <Resource Include="Resources\Images\Icons\Car_Sport.png" />
    <Resource Include="Resources\Images\Icons\Door.png" />
    <Resource Include="Resources\Images\Icons\Open.png" />
    <Resource Include="Resources\Images\Icons\Plus.png" />
    <Resource Include="Resources\Images\Icons\Save.png" />
    <Resource Include="Resources\Images\Icons\Share.png" />
    <Resource Include="Resources\Images\Matrix_River.png" />
  </ItemGroup>

</Project>
